In [2]:
import pandas as pd

In [6]:
data = pd.read_csv("inventory_solids.csv")

In [7]:
data.columns= ["name","sum_formula","amount(g)"]
data

             name  sum_formula  amount(g)
0  sodium sulfate       Na2SO4        980
1  copper acetate       CuOAc2        100
2         quinine   C20H24N2O2         45
3  copper acetate       CuOAc2         32
4  copper bromide         CuBr         56
5  copper acetate       CuOAc2        250

In [9]:

data.iloc[:,1]
data.iloc[1,1]= "New Value" #change a value in a certain row and column

data.values[1]# returns all values in certain row

data

             name  sum_formula  amount(g)
0  sodium sulfate       Na2SO4        980
1  copper acetate    New Value        100
2         quinine   C20H24N2O2         45
3  copper acetate       CuOAc2         32
4  copper bromide         CuBr         56
5  copper acetate       CuOAc2        250

In [11]:
data["amounts(kg)"]= data["amount(g)"]/1000 #create a new column by performing an operation on an existing column
data

             name  sum_formula  amount(g)  amounts(kg)
0  sodium sulfate       Na2SO4        980        0.980
1  copper acetate    New Value        100        0.100
2         quinine   C20H24N2O2         45        0.045
3  copper acetate       CuOAc2         32        0.032
4  copper bromide         CuBr         56        0.056
5  copper acetate       CuOAc2        250        0.250

In [ ]:
#remove stuff
data["amounts(mg)"]= data["amount(g)"]*1000 #create a new column by performing an operation on an existing column

data.dropna #would drop all missing values 

data.drop(["amounts(mg)"],axis=1, inplace = True) #inplace = True means that the changes are made to the original. inplace= false just uses a copy of the data. 
#axis=1 means that we are dropping a column, axis=0 would mean dropping a row
#or
data2=data.drop(["amount(g)"],axis=1, inplace = False) #copy
data2
 
data

             name  sum_formula  amount(g)  amounts(kg)
0  sodium sulfate       Na2SO4        980        0.980
1  copper acetate    New Value        100        0.100
2         quinine   C20H24N2O2         45        0.045
3  copper acetate       CuOAc2         32        0.032
4  copper bromide         CuBr         56        0.056
5  copper acetate       CuOAc2        250        0.250

In [23]:
data2.drop(columns=["amounts(kg)"], inplace = True)
data2

             name  sum_formula
0  sodium sulfate       Na2SO4
1  copper acetate    New Value
2         quinine   C20H24N2O2
3  copper acetate       CuOAc2
4  copper bromide         CuBr
5  copper acetate       CuOAc2

In [ ]:
data2.loc(len(data))=["sodium chloride", "NaCl", 1000, 1] #add a new row to the data frame. The first argument is the index of the new row, the second argument is a list of values for the new row.
data2.drop(6, inplace = True) #drop a row by index
#or data2.drop(data.index[6], inplace = True) #drop a row by index

data2

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (116665209.py, line 1)

In [34]:
data3= data2.copy()

data4= pd.concat([data2,data3], ignore_index=False, axis=1)  #concatenate two dataframes. ignore_index=True means that the index will be reset to a continuous range of integers.
data3
data4

,name,sum_formula,amounts(kg),name,sum_formula,amounts(kg)
0,sodium sulfate,Na2SO4,0.980,sodium sulfate,Na2SO4,0.980
1,copper acetate,New Value,0.100,copper acetate,New Value,0.100
2,quinine,C20H24N2O2,0.045,quinine,C20H24N2O2,0.045
3,copper acetate,CuOAc2,0.032,copper acetate,CuOAc2,0.032
4,copper bromide,CuBr,0.056,copper bromide,CuBr,0.056
5,copper acetate,CuOAc2,0.250,copper acetate,CuOAc2,0.250

In [36]:
data4.to_csv("complete inventory.csv", index=False) #save the data frame to a csv file. index=False means that the implicit index will not be saved to the file.

In [37]:
data5= pd.concat([data2,data3], ignore_index=False, axis=0)
data5

             name  sum_formula  amounts(kg)
0  sodium sulfate       Na2SO4        0.980
1  copper acetate    New Value        0.100
2         quinine   C20H24N2O2        0.045
3  copper acetate       CuOAc2        0.032
4  copper bromide         CuBr        0.056
5  copper acetate       CuOAc2        0.250
0  sodium sulfate       Na2SO4        0.980
1  copper acetate    New Value        0.100
2         quinine   C20H24N2O2        0.045
3  copper acetate       CuOAc2        0.032
4  copper bromide         CuBr        0.056
5  copper acetate       CuOAc2        0.250

In [43]:
#clean up repetitions etc. 

data5.groupby("name").sum() #group by name and sum the amounts. This will give us the total amount of each chemical in the inventory.
#aslo sums strings, not only numerical values
data5["amounts(kg)"].idxmax()

np.int64(0)

In [44]:
data5.describe() #gives us a summary of the data frame, including count, mean, std, min, max, and quartiles for each numerical column.

       amounts(kg)
count    12.000000
mean      0.243833
std       0.352228
min       0.032000
25%       0.045000
50%       0.078000
75%       0.250000
max       0.980000

In [ ]:
data5.info() #gives summary statistics.

<class 'pandas.DataFrame'>
Index: 12 entries, 0 to 5
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         12 non-null     str
 1   sum_formula  12 non-null     str
 2   amounts(kg)  12 non-null     float64
dtypes: float64(1), str(2)
memory usage: 630.0 bytes

In [ ]:
data5["newamount"]=data5["amounts(kg)"].apply(lambda x:x+100) #create a new column by performing an operation on an existing column
#after apply you can put in any function. eg. also logics, booleans, etc. 
data5

             name  sum_formula  amounts(kg)  newamount
0  sodium sulfate       Na2SO4        0.980    100.980
1  copper acetate    New Value        0.100    100.100
2         quinine   C20H24N2O2        0.045    100.045
3  copper acetate       CuOAc2        0.032    100.032
4  copper bromide         CuBr        0.056    100.056
5  copper acetate       CuOAc2        0.250    100.250
0  sodium sulfate       Na2SO4        0.980    100.980
1  copper acetate    New Value        0.100    100.100
2         quinine   C20H24N2O2        0.045    100.045
3  copper acetate       CuOAc2        0.032    100.032
4  copper bromide         CuBr        0.056    100.056
5  copper acetate       CuOAc2        0.250    100.250